# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vegetables', '0002_auto_20180711_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='product',
            new_name='item',
        ),
    ]
