# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vegetables', '0003_auto_20180711_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='item',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ManyToManyField(to='Vegetables.Item'),
        ),
    ]
