# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_name',
            field=models.ManyToManyField(to='Purchase.Purchase'),
        ),
    ]
