# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='North_Indian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('food_items', models.IntegerField(default=400)),
                ('discount', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='South_Indian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('food_items', models.IntegerField(default=400)),
                ('discount', models.IntegerField(default=100)),
            ],
        ),
    ]
