# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_stall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='north_indian',
            name='id',
        ),
        migrations.AlterField(
            model_name='north_indian',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
