# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=250)),
                ('manager', models.CharField(max_length=250)),
                ('transport', models.CharField(max_length=250)),
                ('labor_salary', models.IntegerField()),
                ('cur_year_earnings', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=250)),
                ('journal_desc', models.TextField()),
                ('account', models.ManyToManyField(to='Accounts.Account')),
            ],
            options={
                'db_table': 'journals',
            },
        ),
    ]
