# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer_Groceries',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer',
            new_name='customer_groceries',
        ),
        migrations.AlterModelTable(
            name='customer_groceries',
            table='customer_groceries',
        ),
    ]
