# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morning_shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shows', models.IntegerField(default=12)),
                ('ticket_price', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'Morning_shows',
            },
        ),
        migrations.CreateModel(
            name='Night_shows',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('shows', models.IntegerField(default=8)),
                ('ticket_price', models.IntegerField(default=150)),
            ],
            options={
                'db_table': 'Night_shows',
            },
        ),
    ]
