# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile_num', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=254)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Sales_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sales_person', models.CharField(max_length=250)),
                ('shipping_method', models.CharField(max_length=250)),
                ('delivery_date', models.DateField()),
                ('types', models.CharField(choices=[('online', 'Online Payment'), ('COD', 'Cash On Delivery')], max_length=10)),
                ('cust_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Customer')),
            ],
            options={
                'db_table': 'sales_order',
            },
        ),
    ]
