# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
