# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=250)),
                ('warehouse_address', models.TextField()),
                ('mobile', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=250)),
                ('workers_count', models.IntegerField()),
                ('workers_salary', models.IntegerField()),
                ('rack_storage', models.IntegerField()),
                ('warehou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.Location')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
    ]
