# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehou',
            new_name='warehou_key',
        ),
    ]
